### ISSUE TITLE
channel 사용 질문

### ISSUE THREAD

**Issue by boojongmin** [konan8205/xingapi-rs#5]
소스코드에서 의도가 궁금해서 질문을 올립니다.

일반적으로 xingapi-rs에서 channel을 생성시 unbounded_channel로 만드었는데

![image](https://user-images.githubusercontent.com/9567723/133895951-8a58cf67-9928-4e23-a849-b8f9e86a7117.png)

위의 이미지처럼 일부는 capacity를 1로 주어서 채널의 크기를 정해주었습니다.

너무 빠른 동작에서 기존에 1개가 들어가 있어 새로운값이 채널에 넣지 못한다거나 오동작을 할 수 있지 않을까하는 부분이 있습니다.

다른 코드랑 다르게 값을 명시해줬다는건 작성자의 의도가 있는 부분이라 생각이 들어 궁금해서 질문을 올립니다.

감사합니다.

**Comment by konan8205** [comment]
송신과 수신이 구현상 각각 한번씩만 발생하기 때문입니다.
만일 넣을 공간이 없을 경우 패닉이 발생하게끔 되어있습니다.
