### ISSUE TITLE
Linux 타겟이 Docs.rs에 표시되지 않습니다.

### ISSUE THREAD

**Issue by konan8205** [konan8205/xingapi-rs#7]
0.3.1부터 0.3.3까지의 버전은 Docs.rs에서 Linux 타겟이 표시되지 않는 문제를 해결하기 위해 릴리즈되었습니다.
그러나 Linux에서 모든 tests가 동작하고 examples가 빌드되도록 수정하였음에도 불구하고 해결되지 않았습니다.

Docs.rs에 버그가 있는 것 같습니다.
rust-lang/docs.rs#1556

**Comment by ian-wazowski** [comment]
Excellent work!

**Comment by ian-wazowski** [comment]
Are there any issues need to solve?

**Comment by konan8205** [comment]
@ian-wazowski Production code is not affected. It's probably just a bug in Docs.rs. See https://github.com/rust-lang/docs.rs/issues/1556#issuecomment-974803602.
